<?php

namespace Bedrijven\FicheBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BedrijfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BedrijfRepository extends EntityRepository
{
    public function getLatestBedrijven($limit = null)
    {
        $qb = $this->createQueryBuilder('b')
                   ->select('b')
                   ->addOrderBy('b.created', 'DESC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                  ->getResult();
    }
}