<?php

namespace Bedrijven\FicheBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactpersoonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactpersoonRepository extends EntityRepository
{
    public function getContactpersonenForBedrijf($bedrijfId)
    {
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.bedrijf = :bedrijf_id')
                   ->addOrderBy('c.created')
                   ->setParameter('bedrijf_id', $bedrijfId);

        return $qb->getQuery()
                  ->getResult();
    }
}
